# Default values for the AI Gateway Helm Chart
# This YAML file declares variables for use in the templates

# -- Array of imagePullSecrets for pulling images from private registries
imagePullSecrets: []


serviceAccount:
  # -- Enable creation of the AI Gateway service account
  create: true

  # -- Annotations for the AI Gateway service account
  annotations: {}
  # -- Service account name to be used
  name:


config:
  # -- Enable creation of the AI Gateway `aigw.yaml` config map
  create: true

  # -- Name of ConfigMap to use
  name:

  # -- The contents of an aigw.yaml configuration file
  contents: |
    mode: standalone

    server:
      address: :4141

    adminServer:
      address: localhost:8080


# License configuration
license:
  # -- Name of the secret that contains the license data
  secretName: f5-license
  # -- Key of the secret which contains the license data
  secretKey: token


# Configuration for the AI Gateway core (aigw) application
aigw:
  # -- Enable the core (aigw) application
  enable: true

  # -- Number of replicas for the aigw deployment
  replicas: 1

  image:
    # -- Repository for the aigw image
    repository: michelangelodorado/aigw

    # -- Version tag for the aigw image
    tag: v0.1.0

    pullPolicy: IfNotPresent

  # -- Configure additional environment variables for the aigw deployment
  env: []

  # Configuration for storage
  storage:
    # -- Enable storage
    enable: false

    persistence:
      # -- Create a volume to store empheral audit data
      enable: false

      # -- Size of persistent volume claim
      size: 1Gi
      # -- Type of persistent volume claim
      storageClass:
      # -- ReadWriteOnce or ReadOnly
      accessMode: ReadWriteOnce

  # Configuration for audit exporter
  exporter:
    # -- Enable audit exporter (storage must also be enable)
    enable: false

    # -- Type of exporter (stdout, s3)
    type: stdout
    # -- Batch size of the exporter
    batchSize: 1
    # -- Remove transactions after exporting
    removeFiles: true
    # -- Number of workers for the exporter
    workers: 1

    # -- Name of S3 bucket to export to
    s3Bucket: ""
    # -- Timeout for uploading a single transaction to S3
    s3UploadTimeout: 30s

  # Configure the health server. If the process is healthy, the server will respond with a 200 response on the /health path
  healthServer:
    # -- Configure the port of the health server
    port: 8081

  # Configuration for the service
  # Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # -- Enable the service
    enable: true

    # -- Type of services for the service
    type: ClusterIP
    # -- Port for the service
    port: 80
    # -- Annotations for the service
    annotations: {}

  # -- Security context for the aigw deployment
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsUser: 101
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  # -- Security context for the aigw pods
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  # -- Annotations for the aigw pods
  annotations: {}

  # -- Affinity rules for the aigw pods
  affinity: {}

  # -- Resource requests and limits for the aigw container
  resources:
    requests:
      cpu: 50m
      memory: 50Mi

  # -- Node selector for scheduling the aigw pods
  nodeSelector: {}

  # -- Tolerations for the aigw pods
  tolerations: []


# Configuration for AI Gateway processors
processors:
  # Configuration for the AI Gateway F5 processors (aigw-processors-f5) application
  f5:
    # -- Enable the F5 processors (aigw-processors-f5) application
    enable: true

    # -- Number of replicas for the aigw-processors-f5 deployment
    replicas: 1

    image:
      # -- Repository for the aigw-processors-f5 image
      repository: michelangelodorado/aigw-processors-f5

      # -- Version tag for the aigw-processors-f5 image
      tag: v0.1.0

      pullPolicy: IfNotPresent

    # -- Configure additional environment variables for the aigw-processors-f5 deployment
    env: []

    # Configuration for the service
    # Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
    service:
      # -- Enable the service
      enable: true

      # -- Type of services for the service
      type: ClusterIP
      # -- Port for the service
      port: 80
      # -- Annotations for the service
      annotations: {}

    # -- Security context for the aigw-processors-f5 deployment
    securityContext:
      fsGroup: 101
      runAsGroup: 101
      runAsUser: 101
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    # -- Security context for the aigw-processors-f5 pods
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL


tracing:
  # -- Endpoint to ship gRPC traces to
  endpoint: ""
