{{- if and .Values.processors.f5.enable .Values.processors.f5.service.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aigw-processors-f5.fullname" . }}
  labels:
    {{- include "aigw.labels" . | nindent 4 }}
    {{- include "aigw-processors-f5.selectorLabels" . | nindent 4 }}
    {{- with .Values.processors.f5.service.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  type: {{ .Values.processors.f5.service.type }}
  ports:
    - name: http
      port: {{ .Values.processors.f5.service.port }}
      targetPort: http
      protocol: TCP
      {{- if .Values.processors.f5.service.nodePort }}
      nodePort: {{ .Values.processors.f5.service.nodePort }}
      {{- end }}
  selector:
    {{- include "aigw-processors-f5.selectorLabels" . | nindent 4 }}
{{- end }}
